opam-version: "2.0"
name: "dozenos1x-config"
version: "0.3"
synopsis: "DozenOS 1.x and EdgeOS config file manipulation library"
description: """
A library for parsing, manipulating, and exporting DozenOS 1.x and EdgeOS config files.
"""
maintainer: "Daniil Baturin <daniil@baturin.org>"
authors: "DozenOS maintainers and contributors <maintainers@dozenos.local>"
license: "MIT"
homepage: "https://github.com/dozenos/dozenos1x-config"
bug-reports: "https://phabricator.dozenos.net"
dev-repo: "git+https://github.com/dozenos/dozenos1x-config/"
build: [
  ["dune" "subst"] {pinned}
  ["dune" "build" "-p" name]
]
depends: [
  "ocamlfind" {build}
  "menhir" {build}
  "dune" {build & >= "1.4.0"}
  "ppx_deriving_yojson" {build & <= "3.9.1"}
  "yojson"
]
